apiVersion: v1
kind: Service
metadata:
  name: {{ include "vllm-chart.fullname" . }}-prometheus
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    {{- include "vllm-chart.selectorLabels" . | nindent 4 }} 